cacheFolder: ./.yarn/shared-cache

globalFolder: ./.yarn/shared-global

installStatePath: ./.yarn/install-state.gz

nodeLinker: node-modules

plugins:
  - checksum: 5d48a2fe5cac94f5f9e762174c914cc10492bdac025c68ef46399716a984068aee5493a30b6e3c22696b76f81ef60e58b48159f314ede3b87af03502cc9c10df
    path: .yarn/plugins/@yarnpkg/plugin-worktree-isolation.cjs
    spec: "https://unpkg.com/@goodfoot/yarn-plugin-worktree-isolation@1.1.1/bundles/@yarnpkg/plugin-worktree-isolation.js"
