cacheFolder: ./.yarn/shared-cache

globalFolder: ./.yarn/shared-global

installStatePath: ./.yarn/install-state.gz

nodeLinker: node-modules

packageExtensions:
  "@oxc-resolver/binding-wasm32-wasi@*":
    dependencies:
      "@emnapi/core": ^1.7.1
      "@emnapi/runtime": ^1.7.1

plugins:
  - checksum: 71b9bf5b352b607ff11262e8c31ea678475fa400b3d68aa2d6b1e215498258060099cdd354e9a26ed624d413dfb82aef6d84874786705404f12ef4d9051fc124
    path: .yarn/plugins/@yarnpkg/plugin-worktree-isolation.cjs
    spec: "https://unpkg.com/@goodfoot/yarn-plugin-worktree-isolation/bundles/@yarnpkg/plugin-worktree-isolation.js"
