#!/bin/sh
# Generated by wiki mesh scaffold
# Review names and whys before running. Commit: git mesh commit <name>

# ── src/notes.wiki.md ───────────────────────────────────────────

git mesh add wiki/billing/lives \
  src/notes.wiki.md \
  src/charge.ts#L2-L7
git mesh why wiki/billing/lives -m "Implementation lives in handleCharge."

# ── wiki/billing.md ─────────────────────────────────────────────

git mesh add wiki/billing/validates \
  wiki/billing.md \
  src/checkout.ts#L2-L8
git mesh why wiki/billing/validates -m "The billing service validates the checkout payload before submitCheckout is called."

git mesh add wiki/billing/charge \
  wiki/billing.md \
  src/charge.ts#L2-L7
git mesh why wiki/billing/charge -m "The server-side handler handleCharge validates the schema and dispatches to Stripe."

# ── wiki/cli/parser.md ──────────────────────────────────────────

git mesh add wiki/cli/argument-1 \
  wiki/cli/parser.md \
  src/parser.rs#L2-L4
git mesh why wiki/cli/argument-1 -m "The argument parser entrypoint is parse_args."

git mesh add wiki/cli/argument-2 \
  wiki/cli/parser.md \
  src/parser.rs#L2-L4
git mesh why wiki/cli/argument-2 -m "See also a second link for dedup: parse_args."

