use std::path::Path;

use miette::Result;

/// Run the `wiki mesh scaffold` subcommand.
///
/// Phase A: prints only the header banner (shell mode) or `[]` (JSON mode).
/// Name/why generation is deferred to later phases.
pub fn run(globs: &[String], json: bool, _repo_root: &Path) -> Result<i32> {
    let _ = globs; // used in later phases
    if json {
        println!("[]");
    } else {
        print!("{}", SHELL_HEADER);
    }
    Ok(0)
}

const SHELL_HEADER: &str = "#!/bin/sh\n\
# Generated by wiki mesh scaffold\n\
# Review names and whys before running. Commit: git mesh commit <name>\n";
